2024-10-14 21:23:14,686 ERROR: Exception on /edit_profile [GET] [in /home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/sololobo/microblog/app/routes.py", line 120, in edit_profile
    form = EditProfileForm()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2024-10-15 16:46:36,333 INFO: Microblog startup [in /home/sololobo/microblog/app/__init__.py:62]
2024-10-15 17:25:04,204 INFO: Microblog startup [in /home/sololobo/microblog/app/__init__.py:62]
2024-10-15 17:25:17,860 ERROR: Exception on /edit_profile [GET] [in /home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/sololobo/microblog/app/routes.py", line 128, in edit_profile
    form = EditProfileForm()
  File "/home/sololobo/microblog/.venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_username'
2024-10-15 18:08:18,688 INFO: Microblog startup [in /home/sololobo/microblog/app/__init__.py:62]
